// source, destination, type
const redirects = [
  ['/should-redirect-301','/',301],
  ['/should-redirect-302','/',302],
  ['/contact-us','/contact',301],
  ['/classes','http://classes.pint.com',301],
  ['/assets/001/5039.swf','/',301],
  ['/help','/',301],
  ['/holiday_10','/',301],
  ['/index.htm','/',301],
  ['/iphone/another-successful-launch.htm','/',301],
  ['/key/ASWD56425CSA','/',301],
  ['/program?p1=foo&p2=bar','/',301],
  ['/workshop/cgidemo','/',301],
  ['/workshop/cgidemo/client.html','/',301],
  ['/workshop/javascript.htm','/',301],
  ['/Workshop/mech1-9.htm','/',301],
  ['/Workshop/mechi-io.htm','/',301],
  ['/workshop/webmech','/',301],
  ['/workshop/webmech/Past/1.4/WM1.4.p14.htm','/',301],
  ['/workshop/webmech/Past/1.6/Onepage.htm','/',301],
  ['/workshop/webmech/Past/1.7/WM1.7.p1.htm','/',301],
  ['/contact-us','/contact',301],
  ['/contact/mexico','/contact',301],
  ['/clients/client-list.htm','/our-clients',301],
  ['/clients/financial-and-law.htm','/our-clients',301],
  ['/clients/health-care.htm','/our-clients',301],
  ['/clients/high-tech.htm','/our-clients',301],
  ['/clients/industries','/our-clients',301],
  ['/clients/professional-associations.htm','/our-clients',301],
  ['/pint-loves-allergan/pint-loves-allergan-a-lot.htm','/our-clients',301],
  ['/privacy','/privacy-policy',301],
  ['/design-gallery','/what-we-do',301],
  ['/design/backtext.htm','/what-we-do',301],
  ['/design/rgbchart.htm','/what-we-do',301],
  ['/flash/design.swf','/what-we-do',301],
  ['/flash/hosting.swf','/what-we-do',301],
  ['/flash/mobile_applications.swf','/what-we-do',301],
  ['/flash/services_dock_sm.swf','/what-we-do',301],
  ['/flash/services_dock.swf','/what-we-do',301],
  ['/flash/site_security.swf','/what-we-do',301],
  ['/flash/strategy_planning.swf','/what-we-do',301],
  ['/san-diego-web-development','/what-we-do',301],
  ['/services','/what-we-do',301],
  ['/services/analytics.htm','/what-we-do',301],
  ['/services/content_management.htm','/what-we-do',301],
  ['/services/development.htm','/what-we-do',301],
  ['/services/online-marketing.htm','/what-we-do',301],
  ['/services/optimization.htm','/what-we-do',301],
  ['/services/security.htm','/what-we-do',301],
  ['/services/strategy.htm','/what-we-do',301],
  ['/zingchart-javascript-charts','/what-we-do',301],
  ['/about/bio_tap.htm','/who-we-are',301],
  ['/company','/who-we-are',301],
  ['/company/awards.htm','/who-we-are',301],
  ['/company/leadership','/who-we-are',301],
  ['/company/leadership/eric-samuelson.htm','/who-we-are',301],
  ['/company/leadership/index.htm','/who-we-are',301],
  ['/company/leadership/jimmy-tam.htm','/who-we-are',301],
  ['/company/leadership/thomas-powell','/who-we-are',301],
  ['/Staff/thomas.htm','/who-we-are',301],
  ['/staff/whitworth/tvague/door.htm','/who-we-are',301],
  ['/staff/whitworth/tvague/hakim/bey1.htm','/who-we-are',301],
  ['/staff/whitworth/tvague/hakim/bey3.htm','/who-we-are',301],
  ['/staff/whitworth/tvague/lamonte/young1.htm','/who-we-are',301],
  ['/staff/whitworth/tvague/lamonte/young3.htm','/who-we-are',301],
  ['/staff/whitworth/tvague/links/blake.htm','/who-we-are',301],
  ['/classes','http://classes.pint.com/',301],
  ['/classes/cse130','http://classes.pint.com/',301],
  ['/classes/cse190','http://classes.pint.com/',301],
  ['/classes/javascript2','http://classes.pint.com/',301],
  ['/classes/web1/slides.htm','http://classes.pint.com/',301],
  ['/classes/web2/exercises/Ex4.htm','http://classes.pint.com/',301],
  ['/classes/web3','http://classes.pint.com/',301],
  ['/classes/web3/meeting2/lecture2.pdf','http://classes.pint.com/',301],
  ['/classes/web4','http://classes.pint.com/',301],
  ['/classes/xhtml2','http://classes.pint.com/',301],
  ['/student-resources','http://classes.pint.com/',301],
  ['/classes/cse134b','http://classes.pint.com/cse134b/',301],
  ['/classes/cse135','http://classes.pint.com/cse135/',301],
  ['/blog/2015/06/26/managing-virtual-teams/comment-page-1/','https://blog.pint.com/',301],
  ['/company/news/a-new-dynamic.htm','https://blog.pint.com/',301],
  ['/company/news/pint-designs-new1735.htm','https://blog.pint.com/',301],
  ['/company/news/pint-inc-announces.htm','https://blog.pint.com/',301],
  ['/company/news/pint-rebuilds-immunogen16493.htm','https://blog.pint.com/',301],
  ['/company/careers','https://pint.workable.com/',301],
  ['/company/careers/job_20111207.htm','https://pint.workable.com/',301],
  ['/.br','/',301],
  ["/'",'/',301],
  ['/clients/practice-areas/financial-and-law.htm','/what-we-do',301],
  ['/company/news/a-new-dynamic.htm','/who-we-are',301],
  ['/services/online-marketing.htm','/what-we-do',301],
  ['/company/leadership/eric-samuelson.htm','/who-we-are',301],
  ['/zingchart-javascript-charts','/what-we-do',301],
  ['/iphone/another-successful-launch.htm','/what-we-do',301],
  ['/classes/web1/slides.htm','/what-we-do',301],
  ['/company/leadership/thomas-powell','/who-we-are',301],
  ['/company','/who-we-are',301],
  ['/company/careers/job_20111207.htm','/who-we-are',301],
  ['/staff/whitworth/tvague/links/blake.htm','/who-we-are',301],
  // BLOG REDIRECT
  ['/blog/', 'https://blog.pint.com/',301],
  ['/blog/:tail*', 'https://blog.pint.com/:tail',301],
  // NON-WWW to WWW REDIRECT
  // ['/', 'https://www.pint.com',301],
  // ['/:tail*', 'https://www.pint.com/:tail*',301],
];

module.exports = redirects.map(redirect => {
  return {
    source: redirect[0],
    destination: redirect[1],
    type: redirect[2],
  };
});

